# Site
repository: JingMatrix/about
favicon: images/favicon.ico

# Personal info
name: Jianyu Ma
title: Student
email: jingmatrix@gmail.com
# phone: Your phone number (optional)
website: https://jingmatrix.github.io/

# Social links
# twitter_username: jekyllrb
github_username:  JingMatrix
stackexchange_username: "458137"
# dribbble_username: jekyll
facebook_username: jianyu.ma.796
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# youtube_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
about_title: About Me
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
  I am a graduate student in mathematics and I am currently studying at Toulouse, France.

  I was born on October 26th, 1998. However, you may already know that many Chinese people use a different [calendar](https://en.wikipedia.org/wiki/Chinese_calendar), so my birthday :birthday: 'changes' every year.

  I like to write [:pencil2:](/blog/), but mainly in Chinese. In my [Math Blog](https://jingmatrix.github.io/articles/writings/2019-12-21-Workflow) , I post the following:
    - Math notes
    - Computer program scripts
    - Excerpts from mathematical articles
  
  My collection of math notes and ebooks is shared on [Google Drive](https://drive.google.com/drive/folders/1O279emuW9Z1LGmQ94fbRYfjZoxT8bpwU?usp=sharing).
   
  In a sense, my taste is a bit retro:
    - For musician :musical_note:, I prefer [Beethoven](https://fr.wikipedia.org/wiki/Ludwig_van_Beethoven).
    - For director :movie_camera:, I prefer [Béla Tarr](https://fr.wikipedia.org/wiki/B%C3%A9la_Tarr), all of his movies are Black-and-White.
    - For writer :books:, I prefer Nietzsche, especially his [Par-delà le bien et le mal](https://fr.wikipedia.org/wiki/Par-del%C3%A0_le_bien_et_le_mal).

  If interested, you can find :egg: in [Matrix](https://jingmatrix.github.io):stuck_out_tongue_winking_eye:.


# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jemoji
